# USE IN THE DOCKER TERMINAL
# RUN: docker-compose up
# Package should be served at  http://192.168.99.100:3500/
version: "3"

services:
  postgres:
    image: "postgres:latest"
  redis:
    image: redis
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3050:80
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    restart: on-failure
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
